apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: prathyand/thebitbeta:auth_module_latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DB_HOSTS
          value: "mongod-0.mongodb-service,mongod-1.mongodb-service:27017"
        - name: DB_REPLICASET
          value: "MainRepSet"
        - name: PREFS
          value: "directConnection=true&readPreference=primaryPreferred"
        - name: DB_DATABASE_AUTH
          value: "authDB"
        - name: environment
          value: "kubernetes"
        - name: APP_PORT
          value: "3001"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
