apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000  # gateway service NodePort
    hostPort: 30000
    listenAddress: "0.0.0.0"
    protocol: tcp 
  - containerPort: 31000  # frontend service NodePort
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: tcp 
~                                              