version: "3.8"

services:
  mongodb:
    container_name: thebit_mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - thebitdb:/data/db

  auth_service:
    container_name: auth_service
    depends_on:
      - mongodb
    build: ./auth_service
    restart: unless-stopped
    environment:
      - DB_HOSTS=thebit_mongo:27017
      - DB_DATABASE_AUTH=authDB
      - APP_PORT=3001
      - environment=docker
      - RABBITMQ_HOST=thebit_rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=reset_password_queue
    ports:
      - 3001:3001

  dashboard_service:
    container_name: dashboard_service
    depends_on:
      - mongodb
      - auth_service
      - rabbitmq
    build: ./dashboard_service
    restart: unless-stopped
    environment:
      - DB_HOSTS=thebit_mongo:27017
      - DB_DATABASE=serv_DB
      - APP_PORT=3002
      - RABBITMQ_HOST=thebit_rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=email_worker_queue
    ports:
      - 3002:3002

  notification_service:
    container_name: notification_service
    depends_on:
      - dashboard_service
      - rabbitmq
    build: ./notification_service
    restart: on-failure
    environment:
      - RABBITMQ_HOST=thebit_rabbitmq
      - RABBITMQ_PORT=5672
      - QUEUE_NAME=email_worker_queue&reset_password_queue
    tty: true
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'thebit_rabbitmq'
    hostname: "thebit_rabbitmq"
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - queue:/var/lib/rabbitmq/
      - queue:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 30s
      timeout: 10s
      retries: 5

  api_gateway:
    container_name: api_gateway
    depends_on:
      - mongodb
      - auth_service
      - dashboard_service
      - rabbitmq
    build: ./api_gateway
    restart: unless-stopped
    environment:
      - AUTH_CONTAINER_HOSTNAME=auth_service
      - AUTH_PORT=3001
      - DASHBOARD_CONTAINER_HOSTNAME=dashboard_service
      - DASHBOARD_PORT=3002
      - APP_PORT=5001
    ports:
      - 5001:5001

  web_app:
    container_name: thebit_web_app
    restart: unless-stopped
    build: 
      context: ./frontend
    depends_on:
      - api_gateway
    ports:
      - 80:80
    environment:
      - REACT_APP_GATEWAY=api_gateway
      - GATEWAY1_PORT=5001

    stdin_open: true
    tty: true

volumes:
  thebitdb:
  queue: