version: "3.8"

services:
  mongodb:
    container_name: thebit_mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - thebitdb:/data/db

  auth_service:
    container_name: auth_service
    depends_on:
      - mongodb
    build: ./auth_service
    restart: unless-stopped
    environment:
      - DB_HOSTS=thebit_mongo:27017
      - DB_DATABASE_AUTH=authDB
      - APP_PORT=3001
    ports:
      - 3001:3001

  api_gateway:
    container_name: api_gateway
    depends_on:
      - mongodb
      - auth_service
    build: ./api_gateway
    restart: unless-stopped
    environment:
      - AUTH_CONTAINER_HOSTNAME=auth_service
      - AUTH_PORT=3001
      - APP_PORT=5000
    ports:
      - 5000:5000

  web_app:
    container_name: thebit_web_app
    restart: unless-stopped
    build: 
      context: ./frontend
    depends_on:
      - api_gateway
    ports:
      - 3000:80
    environment:
      - GATEWAY1=api_gateway
      - GATEWAY1_PORT=5000

    stdin_open: true
    tty: true

volumes:
  thebitdb: