version: "3.8"

services:
  mongodb:
    container_name: thebit_mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - thebitdb:/data/db

  auth_service:
    container_name: auth_service
    depends_on:
      - mongodb
    image: prathyand/thebitbeta:auth_module_latest
    restart: unless-stopped
    environment:
      - DB_HOSTS=thebit_mongo:27017
      - DB_DATABASE_AUTH=authDB
      - APP_PORT=3001
      - environment="docker_aws"
    ports:
      - 3001:3001

  dashboard_service:
    container_name: dashboard_service
    depends_on:
      - mongodb
      - auth_service
      - rabbitmq
    image: prathyand/thebitbeta:dashboard_service_latest
    restart: unless-stopped
    environment:
      - DB_HOSTS=thebit_mongo:27017
      - DB_DATABASE=serv_DB
      - APP_PORT=3002
      - RABBITMQ_HOST=thebit_rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=email_worker_queue
    ports:
      - 3002:3002

  notification_service:
    image: prathyand/thebitbeta:notification_service_latest
    container_name: notification_service
    depends_on:
      - dashboard_service
      - rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_HOST=thebit_rabbitmq
      - RABBITMQ_PORT=5672
      - QUEUE_NAME=email_worker_queue

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'thebit_rabbitmq'
    hostname: "thebit_rabbitmq"
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - queue:/var/lib/rabbitmq/
      - queue:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5

  api_gateway:
    container_name: api_gateway
    depends_on:
      - mongodb
      - auth_service
      - dashboard_service
      - rabbitmq
    image: prathyand/thebitbeta:api_gateway_latest
    restart: unless-stopped
    environment:
      - AUTH_CONTAINER_HOSTNAME=auth_service
      - AUTH_PORT=3001
      - DASHBOARD_CONTAINER_HOSTNAME=dashboard_service
      - DASHBOARD_PORT=3002
      - APP_PORT=5001
    ports:
      - 5001:5001

  web_app:
    container_name: thebit_web_app
    restart: unless-stopped
    image: prathyand/thebitbeta:frontend_latest
    depends_on:
      - api_gateway
    ports:
      - 80:80

    stdin_open: true
    tty: true

volumes:
  thebitdb:
  queue: